export const STATUS = {
    OK: 'OK',
    ERROR: 'ERROR',
    NOT_FOUND: 'NOT_FOUND',
    AUTH_ERROR: 'AUTH_ERROR',
};

export const MY_LOGO_STICKER = 'CAACAgIAAxkBAAIFI2UREK8tdg0xz6kqUEmYGRrKlqxvAAJQNQAC8IZxSImpIa_aXO3YMAQ'